// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StyleRaku",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "StyleRaku",
            targets: ["AppModule"],
            bundleIdentifier: "me.com.mrjr0722.StyleRaku.StyleRaku",
            teamIdentifier: "D7SCNS9KT5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readWrite),
                .photoLibrary(purposeString: "It asks for access to the photo to add the photo."),
                .camera(purposeString: "It asks for access to the camera to add photos.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)